pub1 = Publisher.create(name: "Marvel")
pub2 = Publisher.create(name: "DC")
pub3 = Publisher.create(name: "Image")

auth1 = Author.create(first_name: "John", last_name: "Smith")
auth2 = Author.create(first_name: "Terry", last_name: "Crews")
auth3 = Author.create(first_name: "Alec", last_name: "Baldwin")

book1 = Book.create(title: "Gone With The Wind", author_id: auth1.id, publisher_id: pub1.id)
book2 = Book.create(title: "Again, Gone With The Wind", author_id: auth1.id, publisher_id: pub2.id)
book3 = Book.create(title: "A Guide To Dance", author_id: auth2.id, publisher_id: pub1.id)
book4 = Book.create(title: "Cooking With Alec", author_id: auth3.id, publisher_id: pub3.id)

format1 = BookFormatType.create(name: "Hardcover", physical: true)
format2 = BookFormatType.create(name: "Paperback", physical: true)
format3 = BookFormatType.create(name: "PDF", physical: false)
format4 = BookFormatType.create(name: "Epub", physical: false)

bf1 = BookFormat.create(book_id: book1.id, book_format_type_id: format1.id)
bf2 = BookFormat.create(book_id: book1.id, book_format_type_id: format4.id)
bf3 = BookFormat.create(book_id: book2.id, book_format_type_id: format1.id)
bf4 = BookFormat.create(book_id: book2.id, book_format_type_id: format2.id)
bf5 = BookFormat.create(book_id: book2.id, book_format_type_id: format3.id)
bf6 = BookFormat.create(book_id: book2.id, book_format_type_id: format4.id)
bf7 = BookFormat.create(book_id: book3.id, book_format_type_id: format1.id)
bf8 = BookFormat.create(book_id: book4.id, book_format_type_id: format1.id)
bf9 = BookFormat.create(book_id: book4.id, book_format_type_id: format2.id)

br1 = BookReview.create(book_id: book2.id, rating: 3)
br2 = BookReview.create(book_id: book2.id, rating: 4)
br3 = BookReview.create(book_id: book2.id, rating: 4)
br4 = BookReview.create(book_id: book1.id, rating: 2)
br5 = BookReview.create(book_id: book3.id, rating: 5)
br6 = BookReview.create(book_id: book4.id, rating: 1)
